language: java

jdk: oraclejdk8


sudo: required

services:
  - docker

script: 
  - mvn clean test package docker:build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push hexsaw:/logactaesque:latest
    fi
