name: CI Pipeline

on: [push]

jobs:
  build:
    name: Run unit and integration tests, then build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.1
          java-package: jdk
          architecture: x64
      - name: Maven build 
        run: mvn verify
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hexsaw/logactaesque-dice-roller:latest
 
          