name: Java CI with Maven and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.4
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Build with Maven
        run: mvn package
      - name: Dockerize
        run: docker build . --file Dockerfile --tag dice-roller:$(date +%s)
      - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.REGION }}
      - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
            - name: Build, tag, and push image to Amazon ECR
                env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: logactaesque
                  IMAGE_TAG: ${{ github.sha }}
                run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                - name: Logout of Amazon ECR
                  if: always()
                  run: docker logout ${{ steps.login-ecr.outputs.registry }}

